parameters:
  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

stages:

- stage: Build
  condition: and(succeeded(), contains(variables['stages'], 'build'))
  jobs:
  - template: ../jobs/test-images-linux-client.yml
    parameters:
      name: PreBuildValidation
      pool: ${{ parameters.linuxAmd64Pool }}

